import type { ToolDefinition } from './types'

export const rawToolDefinitions: ToolDefinition[] = [
  {
    id: 'json-toolkit',
    title: 'JSON Toolkit',
    category: 'JSON',
    path: '/tools/json-toolkit',
    description: '格式化、压缩、校验 JSON，并给出清晰错误提示。',
    keywords: ['json', 'format', 'minify', 'validate'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported'],
    order: 1,
    loader: () => import('@/views/tools/JsonToolkitView.vue'),
  },
  {
    id: 'qrcode-studio',
    title: 'QRCode Studio',
    category: '二维码',
    path: '/tools/qrcode-studio',
    description: '本地生成二维码，支持尺寸、配色和 PNG 下载。',
    keywords: ['qrcode', 'qr', 'png', 'download', 'share'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported'],
    order: 2,
    loader: () => import('@/views/tools/QrcodeStudioView.vue'),
  },
  {
    id: 'codec-lab',
    title: 'Codec Lab',
    category: '编码',
    path: '/tools/codec-lab',
    description: 'Base64 与 URL 编解码，适合接口调试和临时转换。',
    keywords: ['base64', 'urlencode', 'decode', 'encode'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported'],
    order: 3,
    loader: () => import('@/views/tools/CodecLabView.vue'),
  },
  {
    id: 'diff-studio',
    title: 'Diff Studio',
    category: '对比',
    path: '/tools/diff-studio',
    description: '逐行比较两段文本，查看新增、删除和未变化内容。',
    keywords: ['diff', 'compare', 'patch', 'text', 'line'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported'],
    order: 4,
    loader: () => import('@/views/tools/DiffStudioView.vue'),
  },
  {
    id: 'markdown-studio',
    title: 'Markdown Studio',
    category: '文档',
    path: '/tools/markdown-studio',
    description: '编辑 Markdown 并实时预览，内置常用模板与统计。',
    keywords: ['markdown', 'md', 'preview', 'editor', 'readme'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 5,
    loader: () => import('@/views/tools/MarkdownStudioView.vue'),
  },
  {
    id: 'text-toolkit',
    title: 'Text Toolkit',
    category: '文本',
    path: '/tools/text-toolkit',
    description: '处理大小写、去重排序、空白清洗和行前后缀追加。',
    keywords: ['text', 'trim', 'dedupe', 'sort', 'uppercase', 'lowercase'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 5.5,
    loader: () => import('@/views/tools/TextToolkitView.vue'),
  },
  {
    id: 'csv-toolkit',
    title: 'CSV Toolkit',
    category: '表格',
    path: '/tools/csv-toolkit',
    description: '预览 CSV 表格，支持 CSV / JSON 双向转换与基础清洗。',
    keywords: ['csv', 'table', 'json', 'tsv', 'spreadsheet', 'delimiter'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 5.75,
    loader: () => import('@/views/tools/CsvToolkitView.vue'),
  },
  {
    id: 'sql-formatter',
    title: 'SQL Formatter',
    category: '数据库',
    path: '/tools/sql-formatter',
    description: '格式化或压缩 SQL，统一关键字风格并提升可读性。',
    keywords: ['sql', 'query', 'format', 'database', 'select', 'insert'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 5.8,
    loader: () => import('@/views/tools/SqlFormatterView.vue'),
  },
  {
    id: 'http-lab',
    title: 'HTTP Lab',
    category: '接口',
    path: '/tools/http-lab',
    description: '构造请求、调试响应并查看状态码、响应头和响应体。',
    keywords: ['http', 'api', 'fetch', 'request', 'response'],
    tags: ['network-required', 'favorite-supported'],
    order: 6,
    loader: () => import('@/views/tools/HttpLabView.vue'),
  },
  {
    id: 'request-converter',
    title: 'Request Converter',
    category: '接口',
    path: '/tools/request-converter',
    description: '解析 cURL 并生成 fetch/axios/node-fetch 代码片段。',
    keywords: ['curl', 'fetch', 'axios', 'request', 'snippet'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 7,
    loader: () => import('@/views/tools/RequestConverterView.vue'),
  },
  {
    id: 'url-inspector',
    title: 'URL Inspector',
    category: '接口',
    path: '/tools/url-inspector',
    description: '拆解 URL、编辑 query 参数并重新生成链接，适合联调与回调排查。',
    keywords: ['url', 'query', 'params', 'redirect', 'callback', 'link'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 7.5,
    loader: () => import('@/views/tools/UrlInspectorView.vue'),
  },
  {
    id: 'json-typegen',
    title: 'JSON Typegen',
    category: 'JSON',
    path: '/tools/json-typegen',
    description: '把 JSON 转成 TypeScript 类型和 Zod schema 代码。',
    keywords: ['json', 'typescript', 'zod', 'schema', 'typegen'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 8,
    loader: () => import('@/views/tools/JsonTypegenView.vue'),
  },
  {
    id: 'json-diff-jsonpath',
    title: 'JSON Diff / JSONPath',
    category: 'JSON',
    path: '/tools/json-diff-jsonpath',
    description: '对比两段 JSON 的结构差异，并用 JSONPath 快速提取目标字段。',
    keywords: ['json', 'diff', 'jsonpath', 'compare', 'path', 'query'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 8.25,
    loader: () => import('@/views/tools/JsonDiffJsonPathView.vue'),
  },
  {
    id: 'regex-workbench',
    title: 'Regex Workbench',
    category: '正则',
    path: '/tools/regex-workbench',
    description: '测试表达式、查看分组并预览替换结果。',
    keywords: ['regex', 'regexp', 'match', 'replace', 'groups'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported'],
    order: 9,
    loader: () => import('@/views/tools/RegexWorkbenchView.vue'),
  },
  {
    id: 'jwt-studio',
    title: 'JWT Studio',
    category: '鉴权',
    path: '/tools/jwt-studio',
    description: '本地解析 JWT，查看 header、payload 与过期状态。',
    keywords: ['jwt', 'token', 'auth', 'claims', 'bearer'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 10,
    loader: () => import('@/views/tools/JwtStudioView.vue'),
  },
  {
    id: 'jwt-sign-verify',
    title: 'JWT Sign / Verify',
    category: '鉴权',
    path: '/tools/jwt-sign-verify',
    description: '本地签发和验签 HS256 JWT，并联动展示 header、payload 与状态。',
    keywords: ['jwt', 'sign', 'verify', 'token', 'hs256', 'auth'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 10.5,
    loader: () => import('@/views/tools/JwtSignVerifyView.vue'),
  },
  {
    id: 'hash-studio',
    title: 'Hash Studio',
    category: '校验',
    path: '/tools/hash-studio',
    description: '计算文本或文件的 MD5、SHA-1、SHA-256、SHA-512，并快速比对。',
    keywords: ['hash', 'md5', 'sha256', 'checksum', 'file'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 11,
    loader: () => import('@/views/tools/HashStudioView.vue'),
  },
  {
    id: 'uuid-studio',
    title: 'UUID / NanoID Studio',
    category: '标识',
    path: '/tools/uuid-studio',
    description: '生成 UUID v4 和 NanoID，支持批量生成、长度控制与基础校验。',
    keywords: ['uuid', 'nanoid', 'id', 'identifier', 'random', 'token'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 11.5,
    loader: () => import('@/views/tools/UuidStudioView.vue'),
  },
  {
    id: 'header-cookie-lab',
    title: 'Header & Cookie Lab',
    category: '接口',
    path: '/tools/header-cookie-lab',
    description: '解析 Header/Cookie/Set-Cookie，并支持合并、去重与导出。',
    keywords: ['header', 'cookie', 'set-cookie', 'auth', 'cors'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 12,
    loader: () => import('@/views/tools/HeaderCookieLabView.vue'),
  },
  {
    id: 'websocket-lab',
    title: 'WebSocket Lab',
    category: '接口',
    path: '/tools/websocket-lab',
    description: '轻量 WebSocket 调试台：连接、发消息、心跳与日志。',
    keywords: ['websocket', 'ws', 'wss', 'realtime', 'debug'],
    tags: ['network-required', 'favorite-supported', 'history-supported'],
    order: 13,
    loader: () => import('@/views/tools/WebSocketLabView.vue'),
  },
  {
    id: 'hmac-signer',
    title: 'HMAC Signer',
    category: '鉴权',
    path: '/tools/hmac-signer',
    description: '计算 HMAC-SHA256，并可视化 canonical string 与比对结果。',
    keywords: ['hmac', 'sha256', 'signature', 'auth', 'webhook'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 14,
    loader: () => import('@/views/tools/HmacSignerView.vue'),
  },
  {
    id: 'package-radar',
    title: 'Package Radar',
    category: '包管理',
    path: '/tools/package-radar',
    description: '搜索 npm 包并查看版本、安装命令与官方链接。',
    keywords: ['npm', 'package', 'registry', 'version', 'install'],
    tags: ['network-required', 'favorite-supported'],
    order: 15,
    loader: () => import('@/views/tools/PackageRadarView.vue'),
  },
  {
    id: 'clipboard-history',
    title: 'Clipboard History',
    category: '剪贴板',
    path: '/tools/clipboard-history',
    description: '保存最近的文本片段，支持搜索、置顶、复制和删除。',
    keywords: ['clipboard', 'history', 'snippet', 'copy', 'paste'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 16,
    loader: () => import('@/views/tools/ClipboardHistoryView.vue'),
  },
  {
    id: 'image-studio',
    title: 'Image Studio',
    category: '图片',
    path: '/tools/image-studio',
    description: '本地压缩、裁切、缩放图片，并导出常见格式。',
    keywords: ['image', 'compress', 'resize', 'crop', 'webp'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 17,
    loader: () => import('@/views/tools/ImageStudioView.vue'),
  },
  {
    id: 'color-studio',
    title: 'Color Studio',
    category: '颜色',
    path: '/tools/color-studio',
    description: '转换颜色格式、生成配色方案、预览渐变并检查对比度。',
    keywords: ['color', 'hex', 'rgb', 'hsl', 'gradient'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 18,
    loader: () => import('@/views/tools/ColorStudioView.vue'),
  },
  {
    id: 'time-lab',
    title: 'Time Lab',
    category: '时间',
    path: '/tools/time-lab',
    description: 'Unix 时间戳与日期字符串互转，支持本地时间和 UTC。',
    keywords: ['timestamp', 'time', 'date', 'utc', 'unix'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported'],
    order: 19,
    loader: () => import('@/views/tools/TimeLabView.vue'),
  },
  {
    id: 'cron-planner',
    title: 'Cron Planner',
    category: '调度',
    path: '/tools/cron-planner',
    description: '解释 5 段 cron 表达式，并预览未来触发时间。',
    keywords: ['cron', 'schedule', 'timer', 'job', 'planner'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 20,
    loader: () => import('@/views/tools/CronPlannerView.vue'),
  },
  {
    id: 'calculator-pro',
    title: 'Calculator Pro',
    category: '计算',
    path: '/tools/calculator-pro',
    description: '计算表达式、折扣、税率和均摊结果，并保留历史记录。',
    keywords: ['calculator', 'math', 'discount', 'tax', 'split'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 21,
    loader: () => import('@/views/tools/CalculatorProView.vue'),
  },
  {
    id: 'unit-converter',
    title: 'Unit Converter',
    category: '换算',
    path: '/tools/unit-converter',
    description: '转换长度、重量、温度、存储和速度等常见单位。',
    keywords: ['unit', 'convert', 'length', 'temperature', 'storage'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported', 'history-supported'],
    order: 22,
    loader: () => import('@/views/tools/UnitConverterView.vue'),
  },
  {
    id: 'weather-desk',
    title: 'Weather Desk',
    category: '天气',
    path: '/tools/weather-desk',
    description: '查询城市天气和未来趋势，并支持当前位置天气。',
    keywords: ['weather', 'forecast', 'city', 'temperature', 'rain'],
    tags: ['network-required', 'favorite-supported'],
    order: 23,
    loader: () => import('@/views/tools/WeatherDeskView.vue'),
  },
  {
    id: 'white-noise-studio',
    title: 'White Noise Studio',
    category: '专注',
    path: '/tools/white-noise-studio',
    description: '播放本地生成的环境音，支持叠加、音量和定时停止。',
    keywords: ['noise', 'focus', 'rain', 'ocean', 'sound'],
    tags: ['offline-ready', 'local-processing', 'favorite-supported'],
    order: 24,
    loader: () => import('@/views/tools/WhiteNoiseStudioView.vue'),
  },
]
